### ISSUE TITLE
Update Repo URL in the Rent Receipt Generator (Give our Repo Star)

### ISSUE THREAD

**Issue by saurabh47** [finwis/rent-receipt-generator#8]

**Comment by saurabh47** [comment]
![Image](https://user-images.githubusercontent.com/15173289/229989037-93505af5-8794-4f52-934f-e48ed6351e39.png)

Update this URL to -> https://github.com/finwis/rent-receipt-generator

**Comment by bilalakhter** [comment]
assign me
